//
// ArtworkCreatorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArtworkCreatorsInner: Codable, JSONEncodable, Hashable {

    public var description: String?

    public init(description: String? = nil) {
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

