//
// ArtworksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ArtworksAPI {

    /**
     Artworks List
     
     - parameter apikey: (query) API key 
     - parameter hasimage: (query) Filter to return only artworks that have a image 
     - parameter page: (query) number of page (optional)
     - parameter size: (query) Count of artworks by page (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func everythingGet(apikey: String, hasimage: Int, page: Int? = nil, size: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ArtworksList?, _ error: Error?) -> Void)) -> RequestTask {
        return everythingGetWithRequestBuilder(apikey: apikey, hasimage: hasimage, page: page, size: size).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Artworks List
     - GET /object
     - parameter apikey: (query) API key 
     - parameter hasimage: (query) Filter to return only artworks that have a image 
     - parameter page: (query) number of page (optional)
     - parameter size: (query) Count of artworks by page (optional)
     - returns: RequestBuilder<ArtworksList> 
     */
    open class func everythingGetWithRequestBuilder(apikey: String, hasimage: Int, page: Int? = nil, size: Int? = nil) -> RequestBuilder<ArtworksList> {
        let localVariablePath = "/object"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "apikey": (wrappedValue: apikey.encodeToJSON(), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "size": (wrappedValue: size?.encodeToJSON(), isExplode: true),
            "hasimage": (wrappedValue: hasimage.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ArtworksList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
