//
// ArtworkPeopleInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArtworkPeopleInner: Codable, JSONEncodable, Hashable {

    public var displayname: String?

    public init(displayname: String? = nil) {
        self.displayname = displayname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case displayname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(displayname, forKey: .displayname)
    }
}

