openapi: 3.0.3
info:
  title: The Cleveland Museum of Art
  description: https://clevelandart.org
  version: 1.0.0
servers:
  - url: https://openaccess-api.clevelandart.org/api/
tags:
  - name: Artworks
    description: The Cleveland Museum of Art Artworks
paths:
  /artworks:
    get:
      tags:
        - Artworks
      summary: Artworks List
      operationId: everythingGet
      parameters:
      - name: skip
        in: query
        description: Number of page
        required: true
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: Limit of artworks by page
        required: true
        schema:
          type: integer
          format: int32
      - name: has_image
        in: query
        description: Filter to return only artworks that have a web image asset
        required: true
        schema:
          type: integer
          format: int32
          default: 1
      responses:
                "200":
                  description: success
                  content:
                    application/json:
                      schema:
                       $ref: '#/components/schemas/ArtworksList'
                default:
                 description: enexpected error
                 content:
                   application/json:
                    schema:
                     $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
   ArtworksList:
    type: object
    properties:
     info:
      $ref: '#/components/schemas/Info'
     data:
      type: array
      items:
       $ref: '#/components/schemas/Artwork'
   Info:
    type: object
    properties:
     total:
      type: integer
      format: int32
      nullable: false
   Artwork:
     type: object
     properties:
      id:
       type: integer
       format: int32
      title:
       type: string
      images:
        type: object
        properties:
          web:
            type: object
            properties:
              url:
               type: string
          print:
            type: object
            properties:
              url:
               type: string
          full:
            type: object
            properties:
              url:
               type: string
      description:
        type: string
      creation_date:
        type: string
      creators:
        type: array
        items:
          type: object
          properties:
            description:
              type: string
      technique:
        type: string
   ErrorModel:
    required:
     - status
     - error
    type: object
    properties:
        error:
          type: string
        status:
          maximum: 600
          minimum: 100
          type: integer
        detail:
          type: string
